site_name: ğŸ“š Informatika
site_author: TomÃ¡Å¡ NovotnÃ½
site_url: https://tomnovota.github.io/zs-materialy/

# Repository
# repo_name: zs-materialy
# repo_url: https://github.com/tomnovota/zs-materialy
# edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: cs
  
  # Palette
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: PÅ™epnout na tmavÃ½ reÅ¾im
    
    # Dark mode  
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: PÅ™epnout na svÄ›tlÃ½ reÅ¾im

  # Features
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

  # Icons
  # icon:
  #   repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: date

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - "ğŸ“ 4. roÄnÃ­k":
    - "ğŸ“š VÃ½ukovÃ½ text": 04/index.md
    - "ğŸ“… PlÃ¡n hodin":
      - "4.A Sk1": 04/plan-hodin-4a-sk1.md
      - "4.A Sk2": 04/plan-hodin-4a-sk2.md
    - "ï¿½ HodnocenÃ­": 04/hodnoceni.md
    - "ï¿½ğŸ“– VÃ½uka":
      - "02 PÅ™Ã­klady digitÃ¡lnÃ­ch zaÅ™Ã­zenÃ­, periferie, sloÅ¾enÃ­ poÄÃ­taÄe": 04/vyuka/02/index.md
      - "03 ÃšÄel poÄÃ­taÄÅ¯, bezpeÄnost pÅ™i prÃ¡ci s poÄÃ­taÄem, digitÃ¡lnÃ­ reprezentace": 04/vyuka/03/index.md
      - "04 OperaÄnÃ­ systÃ©m a prvky uÅ¾ivatelskÃ©ho rozhranÃ­": 04/vyuka/04/index.md
      - "05 PrÅ¯zkumnÃ­k souborÅ¯ a prÃ¡ce se soubory": 04/vyuka/05/index.md
      - "06 Aplikace": 04/vyuka/06/index.md
      - "07 SÃ­tÄ›": 04/vyuka/07/index.md
      - "08 Internet": 04/vyuka/08/index.md
      - "09 WebovÃ© strÃ¡nky": 04/vyuka/09/index.md
      - "10 Å ifrovÃ¡nÃ­": 04/vyuka/10/index.md
      - "11 UÅ¾ivatelskÃ© ÃºÄty a autentizace, bezpeÄnÃ© heslo a dvoufÃ¡zovÃ© ovÄ›Å™enÃ­": 04/vyuka/11/index.md
      - "12 Ochrana pÅ™ed Ãºtoky a zÃ¡lohovÃ¡nÃ­": 04/vyuka/12/index.md
      - "13 InformaÄnÃ­ gramotnost a kritickÃ© pÅ™emÃ½Å¡lenÃ­": 04/vyuka/13/index.md
      - "14 Rizika digitÃ¡lnÃ­ch sluÅ¾eb - zÃ¡vislost, soukromÃ­, cizÃ­ lidÃ©, autorstvÃ­": 04/vyuka/14/index.md
      - "15 Algoritmus": 04/vyuka/15/index.md
      - "16 PÅ™Ã­klady algoritmÅ¯": 04/vyuka/16/index.md
      - "17 Ãšlohy na algoritmizaci": 04/vyuka/17/index.md
      - "18 ProgramovacÃ­ jazyky": 04/vyuka/18/index.md
      - "19 ProgramovÃ¡nÃ­ ve Scratch": 04/vyuka/19/index.md
      - "20 ProgramovÃ¡nÃ­ s Ozobotem": 04/vyuka/20/index.md
      - "21 Tisk na 3D tiskÃ¡rnÄ›": 04/vyuka/21/index.md
  - "ğŸ“ 5. roÄnÃ­k":
    - "ğŸ“š VÃ½ukovÃ½ text": 05/index.md
    - "ğŸ“… PlÃ¡n hodin":
      - "5.B Sk1": 05/plan-hodin-5b-sk1.md
      - "5.B Sk2": 05/plan-hodin-5b-sk2.md
    - "ğŸ“Š HodnocenÃ­": 05/hodnoceni.md
    - "ğŸ“– VÃ½uka":
      - "02 PÅ™Ã­klady digitÃ¡lnÃ­ch zaÅ™Ã­zenÃ­, periferie a sloÅ¾enÃ­ poÄÃ­taÄe": 05/vyuka/02/index.md
      - "03 ÃšÄel poÄÃ­taÄÅ¯, bezpeÄnost pÅ™i prÃ¡ci s poÄÃ­taÄem, hesla": 05/vyuka/03/index.md
      - "04 KÃ³dovÃ¡nÃ­ informace": 05/vyuka/04/index.md
      - "05 DigitÃ¡lnÃ­ reprezentace a binÃ¡rnÃ­ soustava": 05/vyuka/05/index.md
      - "06 DatovÃ© typy a komprese dat": 05/vyuka/06/index.md
      - "07 OperaÄnÃ­ systÃ©m a prvky uÅ¾ivatelskÃ©ho rozhranÃ­": 05/vyuka/07/index.md
      - "08 PrÅ¯zkumnÃ­k souborÅ¯ a prÃ¡ce se soubory": 05/vyuka/08/index.md
      - "09 PouÅ¾Ã­vÃ¡nÃ­ aplikacÃ­ a zÃ¡kladnÃ­ aplikace": 05/vyuka/09/index.md
      - "10 SÃ­tÄ›": 05/vyuka/10/index.md
      - "11 Vlastnosti objektÅ¯, jejich Å™azenÃ­ a ÄÃ­slovÃ¡nÃ­": 05/vyuka/11/index.md
      - "12 Data a datasety": 05/vyuka/12/index.md
      - "13 SbÄ›r dat - pozorovÃ¡nÃ­ okolÃ­": 05/vyuka/13/index.md
      - "14 SbÄ›r dat - dotaznÃ­kovÃ© Å¡etÅ™enÃ­": 05/vyuka/14/index.md
      - "15 VyhledÃ¡vÃ¡nÃ­ dat": 05/vyuka/15/index.md
      - "16 UklÃ¡dÃ¡nÃ­ dat a datovÃ© typy": 05/vyuka/16/index.md
      - "17 CloudovÃ© ÃºloÅ¾iÅ¡tÄ›": 05/vyuka/17/index.md
      - "18 ProblÃ©my v datech": 05/vyuka/18/index.md
      - "19 VyhodnocenÃ­ dat": 05/vyuka/19/index.md
      - "20 Grafy": 05/vyuka/20/index.md
      - "21 ZÃ¡vÄ›ry z dat": 05/vyuka/21/index.md
      - "22 ZpracovÃ¡nÃ­ dat a strojovÃ© uÄenÃ­": 05/vyuka/22/index.md
      - "23 PÅ™Ã­klady a ÃºÄel informaÄnÃ­ch systÃ©mÅ¯": 05/vyuka/23/index.md
      - "24 Technologie informaÄnÃ­ch systÃ©mÅ¯, uÅ¾ivatelÃ© a prÃ¡va": 05/vyuka/24/index.md
      - "25 SchÃ©mata": 05/vyuka/25/index.md
    - "ğŸ“Š HodnocenÃ­": 05/hodnoceni.md
  - "ğŸ“ 6. roÄnÃ­k":
    - "ğŸ“š VÃ½ukovÃ½ text": 06/index.md
    - "ğŸ“… PlÃ¡n hodin":
      - "6.C Sk1": 06/plan-hodin-6c-sk1.md
      - "6.C Sk2": 06/plan-hodin-6c-sk2.md
    - "ğŸ“Š HodnocenÃ­": 06/hodnoceni.md
    - "ğŸ“– VÃ½uka":
      - "02 PÅ™Ã­klady digitÃ¡lnÃ­ch zaÅ™Ã­zenÃ­, periferie a sloÅ¾enÃ­ poÄÃ­taÄe": 06/vyuka/02/index.md
      - "03 ÃšÄel poÄÃ­taÄÅ¯, bezpeÄnost pÅ™i prÃ¡ci s poÄÃ­taÄem, hesla": 06/vyuka/03/index.md
      - "04 KÃ³dovÃ¡nÃ­ informace": 06/vyuka/04/index.md
      - "05 DigitÃ¡lnÃ­ reprezentace a binÃ¡rnÃ­ soustava": 06/vyuka/05/index.md
      - "06 DatovÃ© typy a komprese dat": 06/vyuka/06/index.md
      - "07 OperaÄnÃ­ systÃ©m a prvky uÅ¾ivatelskÃ©ho rozhranÃ­": 06/vyuka/07/index.md
      - "08 PrÅ¯zkumnÃ­k souborÅ¯ a prÃ¡ce se soubory": 06/vyuka/08/index.md
      - "09 PouÅ¾Ã­vÃ¡nÃ­ aplikacÃ­ a zÃ¡kladnÃ­ aplikace": 06/vyuka/09/index.md
      - "10 SÃ­tÄ›": 06/vyuka/10/index.md
      - "11 Data a datasety": 06/vyuka/11/index.md
      - "12 SbÄ›r dat - pozorovÃ¡nÃ­ okolÃ­": 06/vyuka/12/index.md
      - "13 SbÄ›r dat - dotaznÃ­kovÃ© Å¡etÅ™enÃ­": 06/vyuka/13/index.md
      - "14 VyhledÃ¡vÃ¡nÃ­ dat": 06/vyuka/14/index.md
      - "15 UklÃ¡dÃ¡nÃ­ dat a datovÃ© typy": 06/vyuka/15/index.md
      - "16 CloudovÃ© ÃºloÅ¾iÅ¡tÄ›": 06/vyuka/16/index.md
      - "17 ProblÃ©my v datech": 06/vyuka/17/index.md
      - "18 VyhodnocenÃ­ dat": 06/vyuka/18/index.md
      - "19 Grafy": 06/vyuka/19/index.md
      - "20 ZÃ¡vÄ›ry z dat": 06/vyuka/20/index.md
      - "21 ZpracovÃ¡nÃ­ dat a strojovÃ© uÄenÃ­": 06/vyuka/21/index.md
      - "22 PÅ™Ã­klady a ÃºÄel informaÄnÃ­ch systÃ©mÅ¯": 06/vyuka/22/index.md
      - "23 Technologie informaÄnÃ­ch systÃ©mÅ¯, uÅ¾ivatelÃ© a prÃ¡va": 06/vyuka/23/index.md
      - "24 Å ifrovÃ¡nÃ­": 06/vyuka/24/index.md
      - "25 UÅ¾ivatelskÃ© ÃºÄty a autentizace": 06/vyuka/25/index.md
      - "26 Ochrana pÅ™ed Ãºtoky a zÃ¡lohovÃ¡nÃ­": 06/vyuka/26/index.md
      - "27 InformaÄnÃ­ gramotnost a kritickÃ© pÅ™emÃ½Å¡lenÃ­": 06/vyuka/27/index.md
      - "28 Rizika digitÃ¡lnÃ­ch sluÅ¾eb - zÃ¡vislost, soukromÃ­, cizÃ­ lidÃ©, autorstvÃ­": 06/vyuka/28/index.md
      - "29 Algoritmus": 06/vyuka/29/index.md
      - "30 PÅ™Ã­klady algoritmÅ¯": 06/vyuka/30/index.md
      - "31 Ãšlohy na algoritmizaci": 06/vyuka/31/index.md
      - "32 VÃ½voj programu - plÃ¡novÃ¡nÃ­, testovÃ¡nÃ­, ladÄ›nÃ­ chyb": 06/vyuka/32/index.md
    - "ğŸ“Š HodnocenÃ­": 06/hodnoceni.md
  - "ğŸ“ 7. roÄnÃ­k":
    - "ğŸ“š VÃ½ukovÃ½ text": 07/index.md
    - "ğŸ“… PlÃ¡n hodin":
      - "7.A Sk1": 07/plan-hodin-7a-sk1.md
      - "7.A Sk2": 07/plan-hodin-7a-sk2.md
      - "7.B Sk1": 07/plan-hodin-7b-sk1.md
      - "7.B Sk2": 07/plan-hodin-7b-sk2.md
    - "ï¿½ HodnocenÃ­": 07/hodnoceni.md
    - "ï¿½ğŸ“– VÃ½uka":
      - "02 PÅ™Ã­klady digitÃ¡lnÃ­ch zaÅ™Ã­zenÃ­, periferie a sloÅ¾enÃ­ poÄÃ­taÄe": 07/vyuka/02/index.md
      - "03 ÃšÄel poÄÃ­taÄÅ¯, bezpeÄnost pÅ™i prÃ¡ci s poÄÃ­taÄem, hesla": 07/vyuka/03/index.md
      - "04 KÃ³dovÃ¡nÃ­ informace a digitÃ¡lnÃ­ reprezentace": 07/vyuka/04/index.md
      - "05 DatovÃ© typy a komprese dat": 07/vyuka/05/index.md
      - "06 OperaÄnÃ­ systÃ©m a prvky uÅ¾ivatelskÃ©ho rozhranÃ­": 07/vyuka/06/index.md
      - "07 PrÅ¯zkumnÃ­k souborÅ¯ a prÃ¡ce se soubory": 07/vyuka/07/index.md
      - "08 PouÅ¾Ã­vÃ¡nÃ­ aplikacÃ­ a zÃ¡kladnÃ­ aplikace": 07/vyuka/08/index.md
      - "09 SÃ­tÄ›": 07/vyuka/09/index.md
      - "10 Internet a pÅ™ipojenÃ­ k internetu": 07/vyuka/10/index.md
      - "11 WebovÃ© strÃ¡nky": 07/vyuka/11/index.md
      - "12 UÅ¾ivatelskÃ© ÃºÄty a autentizace": 07/vyuka/12/index.md
      - "13 Ochrana pÅ™ed Ãºtoky a zÃ¡lohovÃ¡nÃ­": 07/vyuka/13/index.md
      - "14 InformaÄnÃ­ gramotnost a kritickÃ© pÅ™emÃ½Å¡lenÃ­": 07/vyuka/14/index.md
      - "15 Rizika digitÃ¡lnÃ­ch sluÅ¾eb - zÃ¡vislost, soukromÃ­, cizÃ­ lidÃ©, autorstvÃ­": 07/vyuka/15/index.md
      - "16 PÅ™Ã­klady a ÃºÄel informaÄnÃ­ch systÃ©mÅ¯": 07/vyuka/16/index.md
      - "17 Technologie informaÄnÃ­ch systÃ©mÅ¯, uÅ¾ivatelÃ© a prÃ¡va": 07/vyuka/17/index.md
      - "18 SchÃ©mata": 07/vyuka/18/index.md
      - "19 Tvorba digitÃ¡lnÃ­ho obsahu - dokumenty": 07/vyuka/19/index.md
      - "20 Tvorba digitÃ¡lnÃ­ho obsahu - prezentace": 07/vyuka/20/index.md
      - "21 Tvorba digitÃ¡lnÃ­ho obsahu - tabulky": 07/vyuka/21/index.md
      - "22 Tvorba digitÃ¡lnÃ­ho obsahu - rastrovÃ¡ grafika": 07/vyuka/22/index.md
      - "23 VyhledÃ¡vaÄe a AI asistenti": 07/vyuka/23/index.md
      - "24 AutorstvÃ­ a licence, Ochrana osobnÃ­ch ÃºdajÅ¯": 07/vyuka/24/index.md
      - "25 Algoritmus, pÅ™Ã­klady algoritmÅ¯": 07/vyuka/25/index.md
      - "26 Ãšlohy na algoritmizaci, Å™adÃ­cÃ­ a tÅ™Ã­dÃ­cÃ­ algoritmy": 07/vyuka/26/index.md
      - "27 ProgramovacÃ­ jazyky": 07/vyuka/27/index.md
      - "28 VÃ½voj programu - plÃ¡novÃ¡nÃ­, testovÃ¡nÃ­, ladÄ›nÃ­ chyb": 07/vyuka/28/index.md
      - "29 ProgramovÃ¡nÃ­ her v Makecode Arcade": 07/vyuka/29/index.md
    - "ğŸ“Š HodnocenÃ­": 07/hodnoceni.md
  - "ğŸ“ 8. roÄnÃ­k":
    - "ğŸ“š VÃ½ukovÃ½ text": 08/index.md
    - "ğŸ“… PlÃ¡n hodin":
      - "8.B Sk1": 08/plan-hodin-8b-sk1.md
      - "8.B Sk2": 08/plan-hodin-8b-sk2.md
      - "8.C Sk2": 08/plan-hodin-8c-sk2.md
    - "ï¿½ HodnocenÃ­": 08/hodnoceni.md
    - "ï¿½ğŸ“– VÃ½uka":
      - "02 DigitÃ¡lnÃ­ch zaÅ™Ã­zenÃ­, periferie a sloÅ¾enÃ­ poÄÃ­taÄe": 08/vyuka/02/index.md
      - "03 KÃ³dovÃ¡nÃ­ informace": 08/vyuka/03/index.md
      - "04 DigitÃ¡lnÃ­ reprezentace a binÃ¡rnÃ­ soustava": 08/vyuka/04/index.md
      - "05 DatovÃ© typy a komprese dat": 08/vyuka/05/index.md
      - "06 OperaÄnÃ­ systÃ©m, prÅ¯zkumnÃ­k souborÅ¯ a prÃ¡ce se soubory": 08/vyuka/06/index.md
      - "07 SÃ­tÄ›, internet a webovÃ© strÃ¡nky": 08/vyuka/07/index.md
      - "08 Data a datasety": 08/vyuka/08/index.md
      - "09 SbÄ›r dat - pozorovÃ¡nÃ­ okolÃ­": 08/vyuka/09/index.md
      - "10 SbÄ›r dat - dotaznÃ­kovÃ© Å¡etÅ™enÃ­": 08/vyuka/10/index.md
      - "11 SbÄ›r dat - MS Forms": 08/vyuka/11/index.md
      - "12 UklÃ¡dÃ¡nÃ­ dat a datovÃ© typy": 08/vyuka/12/index.md
      - "13 VyhledÃ¡vÃ¡nÃ­ dat a cloudovÃ© ÃºloÅ¾iÅ¡tÄ›": 08/vyuka/13/index.md
      - "14 ProblÃ©my v datech": 08/vyuka/14/index.md
      - "15 VyhodnocenÃ­ dat": 08/vyuka/15/index.md
      - "16 Grafy": 08/vyuka/16/index.md
      - "17 ZÃ¡vÄ›ry z dat": 08/vyuka/17/index.md
      - "18 ZpracovÃ¡nÃ­ dat a strojovÃ© uÄenÃ­": 08/vyuka/18/index.md
      - "19 MS Excel - ruÄnÃ­ vklÃ¡dÃ¡nÃ­ obsahu": 08/vyuka/19/index.md
      - "20 MS Excel - naÄtenÃ­ dat ze souboru, Å™azenÃ­ a filtrovÃ¡nÃ­": 08/vyuka/20/index.md
      - "21 MS Excel - podmÃ­nÄ›nÃ© formÃ¡tovÃ¡nÃ­ a pravidla": 08/vyuka/21/index.md
      - "22 MS Excel - kontingenÄnÃ­ tabulka": 08/vyuka/22/index.md
      - "23 MS Excel - funkce": 08/vyuka/23/index.md
      - "24 MS Excel - vizualizace dat": 08/vyuka/24/index.md
    - "ğŸ“Š HodnocenÃ­": 08/hodnoceni.md
  - "ğŸ“ 9. roÄnÃ­k":
    - "ğŸ“š VÃ½ukovÃ½ text": 09/index.md
    - "ğŸ“… PlÃ¡n hodin":
      - "9.A Sk1": 09/plan-hodin-9a-sk1.md
      - "9.A Sk2": 09/plan-hodin-9a-sk2.md
      - "9.B Sk2": 09/plan-hodin-9b-sk2.md
      - "9.C Sk2": 09/plan-hodin-9c-sk2.md
    - "ğŸ“Š HodnocenÃ­": 09/hodnoceni.md
    - "ğŸ“– VÃ½uka":
      - "02 PÅ™Ã­klady digitÃ¡lnÃ­ch zaÅ™Ã­zenÃ­, periferie a sloÅ¾enÃ­ poÄÃ­taÄe": 09/vyuka/02/index.md
      - "03 KÃ³dovÃ¡nÃ­ informace, digitÃ¡lnÃ­ reprezentace a binÃ¡rnÃ­ soustava": 09/vyuka/03/index.md
      - "04 DatovÃ© typy a komprese dat": 09/vyuka/04/index.md
      - "05 OperaÄnÃ­ systÃ©m - prvky uÅ¾ivatelskÃ©ho rozhranÃ­ a uÅ¾ivatelskÃ© ÃºÄty": 09/vyuka/05/index.md
      - "06 PrÅ¯zkumnÃ­k souborÅ¯ a prÃ¡ce se soubory": 09/vyuka/06/index.md
      - "07 PouÅ¾Ã­vÃ¡nÃ­ aplikacÃ­ a zÃ¡kladnÃ­ aplikace": 09/vyuka/07/index.md
      - "08 SÃ­tÄ›": 09/vyuka/08/index.md
      - "09 CloudovÃ© sluÅ¾by": 09/vyuka/09/index.md
      - "10 Internet a pÅ™ipojenÃ­ k internetu": 09/vyuka/10/index.md
      - "11 OSI model - enkapsulace": 09/vyuka/11/index.md
      - "12 WebovÃ© strÃ¡nky": 09/vyuka/12/index.md
      - "13 Servis poÄÃ­taÄe a Å™eÅ¡enÃ­ technickÃ½ch problÃ©mÅ¯": 09/vyuka/13/index.md
      - "14 Å ifrovÃ¡nÃ­": 09/vyuka/14/index.md
      - "15 UÅ¾ivatelskÃ© ÃºÄty a autentizace": 09/vyuka/15/index.md
      - "16 Ochrana pÅ™ed Ãºtoky a zÃ¡lohovÃ¡nÃ­": 09/vyuka/16/index.md
      - "17 InformaÄnÃ­ gramotnost a kritickÃ© pÅ™emÃ½Å¡lenÃ­": 09/vyuka/17/index.md
      - "18 Rizika digitÃ¡lnÃ­ch sluÅ¾eb - zÃ¡vislost, soukromÃ­, cizÃ­ lidÃ©, autorstvÃ­": 09/vyuka/18/index.md
      - "19 DigitÃ¡lnÃ­ stopa": 09/vyuka/19/index.md
      - "20 Rizika digitÃ¡lnÃ­ identity": 09/vyuka/20/index.md
      - "21 SociÃ¡lnÃ­ sÃ­tÄ› a doporuÄovacÃ­ algoritmy": 09/vyuka/21/index.md
      - "22 UmÄ›lÃ¡ inteligence": 09/vyuka/22/index.md
      - "23 StrojovÃ© uÄenÃ­": 09/vyuka/23/index.md
      - "24 Robotika a drony": 09/vyuka/24/index.md
      - "25 ZpracovÃ¡nÃ­ obrazu a poÄÃ­taÄovÃ© vidÄ›nÃ­": 09/vyuka/25/index.md
      - "26 ZvukovÃ© zpracovÃ¡nÃ­": 09/vyuka/26/index.md
      - "27 VirtuÃ¡lnÃ­ a rozÅ¡Ã­Å™enÃ¡ realita": 09/vyuka/27/index.md
      - "28 Internet vÄ›cÃ­": 09/vyuka/28/index.md
    - "ğŸ“Š HodnocenÃ­": 09/hodnoceni.md
  - "ğŸ“š NÃ¡vody":
    - navody/index.md
    - "ğŸ’» PoÄÃ­taÄovÃ¡ gramotnost":
      - "ğŸŒ± ZdravÃ© pouÅ¾Ã­vÃ¡nÃ­ poÄÃ­taÄe": navody/zdrave-pouzivani-pocitace.md
    - "â˜ï¸ CloudovÃ© sluÅ¾by":
      - navody/office365.md
      - "ğŸ“ OneDrive": navody/onedrive.md
      - "ğŸ“§ Outlook": navody/outlook.md
      - "ğŸ“± Microsoft Teams": navody/teams.md
  - "ğŸ“ Kontakt":
    - kontakt/index.md
    - "ğŸ‘¨â€ğŸ« TomÃ¡Å¡ NovotnÃ½": kontakt/tomas.md
    - "ğŸ‘¨â€ğŸ’» Jan ChmelaÅ™": kontakt/jan.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tomnovota/zs-materialy
    - icon: fontawesome/solid/envelope
      link: mailto:tomas.novotny@zshovorcovicka.cz
      
  # Analytics (optional)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX

# Custom CSS
extra_css:
  - stylesheets/extra.css

# JavaScript  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js